Proje2
Frontend-Mentor-Project/Collective-Projects pull request #28
Opened 2023-01-25 17:07 UTC by GonulAksu

25 ocak

2023-01-25 20:27 UTC, mstfbiccer requested changes
Selamlar @GonulAksu,

- Muhtemelen benim ekran çözünürlüğümden kaynaklı olarak, en üstteki yeşil gridin sağ tarafında fazladan beyazlık bulunuyor. Bunun dışında temel olarak tasarım isteneni karşılıyor. Sadece, orta kutucuklar (turkuaz olanlar)  arasındaki boşluklar figma'daki ile daha orantılı olabilirdi. Normal şartlarda figma ile iletilen tasarımlarda %100 uyum beklenir. Fakat öğrenme sürecinde bunu sadece yorum olarak iletiyorum, PR reddine neden olmaz.

- container için class isimlerine çok güzel başlayıp, daha sonrasında class isimlerini maalesef önemsememişiz. "a" gibi ya da h1 gibi class isimleri vermemek gerekiyor. Class isimleri bulunduğu elementi niteler durumda olmalıdır. Bunu düzeltmenizi rica edeceğim.

- Media query bu projede beklemiyorduk ama yaptığınız için orada da bir yorum eklemek istedim. 330px - 450px genişlikleri arasında çok farklı bir görüntü oluşuyor SERVICES kısmında. Belki revize etmek istersiniz. Etmeseniz de mühim değil bu proje özelinde :)

- ID selector'larını BEM önermemektedir. Çünkü elementlerinizi belirli ortak özelliklere göre sınıflandırarak ilerlemenizi tercih eder. Hem id kullanımı hem de Home gibi büyük harf ile başlanması kısımlarını düzeltmeniz kodumuzu daha temiz hale getirecektir.

Birinci madde dışındakileri düzenlemeniz için değişiklik talep ediyorum. Sonrasında PR'ınızı onaylayabilirim. Elinize & Emeğinize Sağlık.

2023-01-25 23:01 UTC, b-tekinli commented
merhaba, mentorumuzun söyledikleri dışında ben de commitlerinize dikkat etmenizi rica edeceğim. "a" diye commit atmak doğru bir commit şekli değil. yaptığımız işi biraz daha ciddiye almamız ve severek yapmamız gerektiğini düşünüyorum. bunlar dışında sizinle birlikte bir hesabınız daha pr atıyor gibi gözüküyor projede katkısı var gibi yani onu da düzeltirseniz birlikte güzel bir yol katetmiş olacağız.

2023-01-25 23:01 UTC, closed without merging

2023-01-26 10:08 UTC, GonulAksu commented
İncelemelerinizde haklısınız bu şekilde yansıtmak istemezdim daha dikkatli olacağım.
Tek hesabım var ama inceledim tam olarak anlayamadım nasıl öyle gözüküyor?

Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Beyzanur ***@***.***>
Gönderilme: 26 Ocak 2023 Perşembe 02:01
Kime: ***@***.***>
Bilgi: Gönül ***@***.***>; ***@***.***>
Konu: Re: [Frontend-Mentor-Project/Collective-Projects] Proje2 (PR #28)


merhaba, mentorumuzun söyledikleri dışında ben de commitlerinize dikkat etmenizi rica edeceğim. "a" diye commit atmak doğru bir commit şekli değil. yaptığımız işi biraz daha ciddiye almamız ve severek yapmamız gerektiğini düşünüyorum. bunlar dışında sizinle birlikte bir hesabınız daha pr atıyor gibi gözüküyor projede katkısı var gibi yani onu da düzeltirseniz birlikte güzel bir yol katetmiş olacağız.

—
Reply to this email directly, view it on GitHub<https://github.com/Frontend-Mentor-Project/Collective-Projects/pull/28#issuecomment-1404334996>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARPTPFNN2NDF4X24EDFLQADWUGWD7ANCNFSM6AAAAAAUGSE3CY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-26 11:20 UTC, b-tekinli commented
kullanıcı adı "gnlakk" olan biri daha gözüküyor. eğer o da sana ait bir hesapsa dilersen hesabı silebilirsin.